platform :ios, '7.0'
pod 'AFNetworking'
pod 'UMengAnalytics-NO-IDFA'
pod 'MJRefresh'
pod 'Mantle', '~> 1.5.4'
pod 'NJKWebViewProgress'
pod 'RKNotificationHub'
pod 'Masonry'
pod ‘GTSDK'
pod 'SSKeychain'
pod 'INTULocationManager'
pod 'FMDB'
pod 'Fabric'
pod 'Crashlytics'
pod 'KSYGPULive_iOS', :git => 'https://github.com/ksvc/KSYLive_iOS.git'
pod 'Pingpp/Alipay', '~> 2.2.4'
pod 'Pingpp/Wx', '~> 2.2.4'
